create extension if not exists pgcrypto;

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  invite_code text not null unique,
  guest_name text not null,
  family_name text,
  phone text,
  invitation_opened boolean not null default false,
  opened_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.rsvps (
  id uuid primary key default gen_random_uuid(),
  guest_id uuid not null unique references public.guests(id) on delete cascade,
  attending boolean not null,
  total_members integer not null default 0 check (total_members between 0 and 15),
  responded_at timestamptz not null default now()
);

create table if not exists public.settings (
  singleton boolean primary key default true check (singleton),
  wedding_date date not null,
  wedding_time time not null,
  venue_name text not null,
  venue_link text not null,
  rsvp_deadline timestamptz not null
);

create table if not exists public.analytics (
  id bigint generated by default as identity primary key,
  guest_id uuid references public.guests(id) on delete cascade,
  event_type text not null check (event_type in ('invitation_opened', 'rsvp_submitted')),
  created_at timestamptz not null default now()
);

insert into public.settings (singleton, wedding_date, wedding_time, venue_name, venue_link, rsvp_deadline)
values (true, '2026-06-15', '19:00', 'Wedding Reception Venue', 'https://maps.google.com', '2026-06-14T00:00:00+05:30')
on conflict (singleton) do nothing;

alter table public.guests enable row level security;
alter table public.rsvps enable row level security;
alter table public.settings enable row level security;
alter table public.analytics enable row level security;

create policy "Public can read settings"
on public.settings for select
to anon, authenticated
using (true);

-- All privileged writes are performed through the server-side service role client.
